name: Release - Upload Bundle to Play Store

on:
  workflow_dispatch:

env:
  ASANA_PAT: ${{ secrets.GH_ASANA_SECRET }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-nightly-bundle:
    name: Generate and upload nightly bundle to Play Store Internal track
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Decode upload keys
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.UPLOAD_RELEASE_PROPERTIES }}
          fileName: ddg_android_build_upload.properties
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Decode key file
        uses: davidSchuppa/base64Secret-toFile-action@v2
        with:
          secret: ${{ secrets.UPLOAD_RELEASE_KEY }}
          fileName: android
          destination-path: $HOME/jenkins_static/com.duckduckgo.mobile.android/

      - name: Assemble the bundle
        run: ./gradlew bundleInternalRelease -PversionNameSuffix=-nightly -PuseUploadSigning

      - name: Generate nightly version name
        id: generate_version_name
        run: |
          output=$(./gradlew -q getBuildVersionName -PversionNameSuffix=-nightly --quiet)        
          echo "::set-output name=version::$output"

      - name: Use the captured output
        run: |
          echo "The captured output is: ${{ steps.generate_version_name.outputs.version }}"

      - name: Upload bundle to internal
        id: create_app_bundle
        run: |
          bundle exec fastlane deploy_dogfood aab_path:app/build/outputs/bundle/internalRelease/duckduckgo-${{ steps.generate_version_name.outputs.version }}-internal-release.aab          

      - name: Create Asana task when workflow failed
        if: ${{ failure() }}
        id: create-failure-task
        uses: duckduckgo/native-github-asana-sync@v1.1
        with:
          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
          asana-project: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
          asana-section: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
          asana-task-name: GH Workflow Failure - Upload Bundle to Play Store
          asana-task-description: Upload Bundle to Play Store has failed. See https://github.com/duckduckgo/Android/actions/runs/${{ github.run_id }}
          action: 'create-asana-task'